-- step 1 Database creation 
create database Blood_Bank_Management;
use Blood_Bank_Management;

-- step 2 Table creation Statement 
-- Patient table creation
	CREATE TABLE PATIENT(
    PID CHAR(10) PRIMARY KEY,
    BBID CHAR(15),
    PNAME VARCHAR(50),
    PGEN CHAR(10),
    PAGE CHAR(100),
    PCON VARCHAR(55),
    PBG CHAR(20));
    

    
-- HOSPITAL TABLE CREATION
   CREATE TABLE HOSPITAL(
   HID CHAR(100),
   PID CHAR(10),
   BBID CHAR(50),
   HNAME VARCHAR(100),
   HCON VARCHAR(55),
   FOREIGN KEY (PID) REFERENCES PATIENT(PID),
   FOREIGN KEY (BBID) REFERENCES BLOODBANK(BBID)
   );
   
-- BLOODBANK TABLE CREATION
   CREATE TABLE BLOODBANK(
   BBID  CHAR(50) PRIMARY KEY,
   BNAME VARCHAR(100),
   BBCON VARCHAR(50),
   BBADD VARCHAR(100)
   );

-- DONOR TABLE CREATION
CREATE TABLE DONAR(
DID CHAR(50)PRIMARY KEY,
BBID CHAR(50),
DNAME VARCHAR(100),
DBG CHAR(20),
DGEN CHAR(10),
DCON VARCHAR(50),
DON_DATE DATE,
MED_REPO VARCHAR(200),
FOREIGN KEY(BBID) REFERENCES BLOODBANK(BBID)
);

-- BLOOD AVAILABILITY 
CREATE TABLE BLOOD_AVAILABILITY(
BBID CHAR (50),
BG CHAR(20),
QUANTITY bigint,
FOREIGN KEY (BBID) REFERENCES BLOODBANK(BBID)
);